---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: appserver
  name: mytomcat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appserver
  template:
    metadata:
      labels:
        app: appserver
    spec:
      containers:
      - image: amarsmart403/maven-web-application
        name: mytomcat

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: appserver
  name: mytomcat
spec:
  ports:
  - nodePort: 32223
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: appserver
  type: NodePort
